export const AUTH_START ='AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL= 'AUTH_FAIL'
export const AUTH_LOGOUT ='AUTH_LOGOUT'

export const BUDGET_CALCULATE_SUCCESS = 'BUDGET_CALCULATE_SUCCESS'

export const ADD_SUCCESSFUL = 'ADD_SUCCESSFUL'
export const ADD_START ='ADD_START'
export const ADD_FAILED ='ADD_FAILED'

export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS'
export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED'
export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START'